### ISSUE TITLE
compatibility issue with Rarity addon

### ISSUE THREAD

**Issue by Numynum** [NumyAddon/BlizzMovePlugin_ManuscriptsJournal#1]
installing the rarity addon, prevents Manuscripts Journal from being moved

**Comment by Numynum** [comment]
I can't actually reproduce the issue (using latest BM+plugin+rarity+manuscripts journal)

[v1.0.1](https://github.com/NumyAddon/BlizzMovePlugin_ManuscriptsJournal/releases/tag/v1.0.1) might fix it, if there was a problem to begin with 🤷‍♂️

**Comment by Snahkstrasza** [comment]
It did fix it thank you very much, sorry for all the hassle lol

**Comment by teelolws** [comment]
This is probably because Rarity loads during the loading screen but I have internal delays to keep from loading MJ until the collections journal is actually opened.

What is the purpose of this addon, though? My understanding is MJ should just move with the collections journal?

**Comment by Numynum** [comment]
without this addon, you cannot move MJ when it's the open tab, it will move with the CJ only when the CJ is moved from another tab

**Comment by teelolws** [comment]
I see. I could just make all my non-button frames clickthrough to the CollectionsJournal behind it. That should make this unnecessary, no?

**Comment by Numynum** [comment]
ah, didn't notice you're the author of MJ 🙂 
that would probably do the trick yes
